### ISSUE TITLE
Model and Define Policies

### ISSUE THREAD

**Issue by Dobios** [Dobios/SURE_WP3#10]
The goal is to model all of the policies shown in the policy window.  
This can only be done once all of the base-game stuff has been implemented so it will have to wait for now.

**Comment by astonedf** [comment]
[Policies Game v4.xlsx](https://github.com/Dobios/SURE_WP3/files/13389833/Policies.Game.v4.xlsx)
I will reorganise the policies window in game and we need to discuss the effects of each policy, but if you want to start implementing the voting system you can
